# Generated by Django 5.1 on 2024-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_e_commerce', '0002_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
