# Generated by Django 5.1 on 2024-08-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_e_commerce', '0003_alter_usersession_session_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
