# Generated by Django 5.1 on 2024-08-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_e_commerce', '0006_alter_chathistory_chat_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='chat_text',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='response_text',
            field=models.CharField(max_length=3000),
        ),
    ]
